version: '3.7'
services:
  duranta-nginx:
    restart: always
    image: 127.0.0.1:7000/duranta-nginx:latest
    build:
      dockerfile: dockerfiles/nginx/Dockerfile
      context: .
    ports:
      - 8989:80
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 5
        window: 120s
volumes:
  duranta-data_new:
